name: mulled-v1-71775ebbd15c6345c63b5feb709e8bee820f447541a965f8edba21bb4b2af03e
channels:
  - abradle
  - omnia
  - conda-forge
  - rdkit
dependencies:
  - python=3.6
  - yank
  - rdkit=2018.03.2
  - pdbfixer
  - openforcefield=swang
  - pip:
    - duck-xchem
