{% set name = "xchem-duck" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/galaxycomputationalchemistry/duck/archive/conda.tar.gz
  sha256: d0ea07eb1c2025e6861f3e18fa32756c537e18f74fb9eb26ff569ceec9d671ac


build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    #- get_wqb = scripts.get_wqb:main
    - frag_duck=scripts.run_full_from_fragalysis:main
    - duck_chunk=scripts.duck_chunk:main
    - duck_prepare_sys=scripts.duck_prepare_sys:main
    - duck_smd_runs=scripts.duck_smd_runs:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    # - yank
    - rdkit
    # - pdbfixer
    # - openforcefield
    # - boto3
    # - cudatoolkit

test:
  commands:
    - duck_smd_runs -h
    - duck_prepare_sys -h
    - duck_chunk -h
    - get_wqb -h

about:
  home: https://github.com/galaxycomputationalchemistry/duck
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - simonbray
